# Copyright (c) 2023 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

# The `change-detection` job determines which CI workflows to run based on the changes in a pull request or push.
# The outputs of the `change-detection` job can then be used to conditionally run other jobs in the workflow.

name: ❓ • Change Detection
on:
  workflow_call:
    inputs:
      additional-cpp-files:
        description: Additional files to check for C++-related changes
        type: string
        default: ""
      additional-python-files:
        description: Additional files to check for Python-related changes
        type: string
        default: ""
      additional-cd-files:
        description: Additional files to check for CD-related changes
        type: string
        default: ""
    outputs:
      run-cpp-tests:
        description: Whether to run the C++ tests
        value: ${{ jobs.change-detection.outputs.run-cpp-tests || false }}
      run-cpp-linter:
        description: Whether to run the C++ linter
        value: ${{ jobs.change-detection.outputs.run-cpp-linter || false }}
      run-python-tests:
        description: Whether to run the Python tests
        value: ${{ jobs.change-detection.outputs.run-python-tests || false }}
      run-python-linter:
        description: Whether to run the Python linter
        value: ${{ jobs.change-detection.outputs.run-python-linter || false }}
      run-cd:
        description: Whether to run the continuous deployment job
        value: ${{ jobs.change-detection.outputs.run-cd || false }}

permissions:
  contents: read

jobs:
  change-detection:
    name: 🕵️ Check
    runs-on: ubuntu-slim
    timeout-minutes: 1
    outputs:
      run-cpp-tests: ${{ steps.cpp-tests-changes.outputs.run-cpp-tests || false }}
      run-cpp-linter: ${{ steps.cpp-linter-changes.outputs.run-cpp-linter || false }}
      run-python-tests: ${{ steps.python-tests-changes.outputs.run-python-tests || false }}
      run-python-linter: ${{ steps.python-linter-changes.outputs.run-python-linter || false }}
      run-cd: ${{ steps.cd-changes.outputs.run-cd || false }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Get a list of the changed files relevant for the C++ tests
        if: github.event_name == 'pull_request'
        id: changed-cpp-testable-files
        env:
          ADDITIONAL_CPP_FILES: ${{ inputs.additional-cpp-files }}
        uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c # v2.3.0
        with:
          filter: |
            include/**
            mlir/**
            src/**
            test/**
            !test/python/**
            CMakeLists.txt
            cmake/**
            .github/codecov.yml
            .github/workflows/reusable-cpp-tests-ubuntu.yml
            .github/workflows/reusable-cpp-tests-macos.yml
            .github/workflows/reusable-cpp-tests-windows.yml
            .github/workflows/reusable-cpp-coverage.yml
            .github/workflows/reusable-cpp-ci.yml
            .github/workflows/ci.yml
            ${{ env.ADDITIONAL_CPP_FILES }}
      - name: Set a flag for running the C++ tests
        if: >-
          github.event_name != 'pull_request'
          || steps.changed-cpp-testable-files.outputs.all != ''
        id: cpp-tests-changes
        run: >-
          echo "run-cpp-tests=true" >> "${GITHUB_OUTPUT}"
      - name: Get a list of the changed files relevant for the C++ linter
        if: github.event_name == 'pull_request'
        id: changed-cpp-linter-files
        env:
          ADDITIONAL_CPP_FILES: ${{ inputs.additional-cpp-files }}
        uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c # v2.3.0
        with:
          filter: |
            bindings/**
            include/**
            mlir/**
            src/**
            test/**
            !test/python/**
            .clang-tidy
            .github/workflows/reusable-cpp-linter.yml
            .github/workflows/ci.yml
            ${{ env.ADDITIONAL_CPP_FILES }}
      - name: Set a flag for running the C++ linter
        if: >-
          github.event_name != 'pull_request'
          || steps.changed-cpp-linter-files.outputs.all != ''
        id: cpp-linter-changes
        run: >-
          echo "run-cpp-linter=true" >> "${GITHUB_OUTPUT}"
      - name: Get a list of the changed files relevant for the Python tests
        if: github.event_name == 'pull_request'
        id: changed-python-testable-files
        env:
          ADDITIONAL_PYTHON_FILES: ${{ inputs.additional-python-files }}
        uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c # v2.3.0
        with:
          filter: |
            cmake/**
            bindings/**
            include/**
            python/**
            src/**
            test/**/*.py
            tests/**/*.py
            noxfile.py
            pyproject.toml
            uv.lock
            CMakeLists.txt
            .github/codecov.yml
            .github/workflows/reusable-python-linter.yml
            .github/workflows/reusable-python-tests.yml
            .github/workflows/reusable-python-ci.yml
            .github/workflows/ci.yml
            ${{ env.ADDITIONAL_PYTHON_FILES }}
      - name: Set a flag for running the Python tests
        if: >-
          github.event_name != 'pull_request'
          || steps.changed-python-testable-files.outputs.all != ''
        id: python-tests-changes
        run: >-
          echo "run-python-tests=true" >> "${GITHUB_OUTPUT}"
      - name: Get a list of the changed files relevant for the Python linter
        if: github.event_name == 'pull_request'
        id: changed-python-linter-files
        env:
          ADDITIONAL_PYTHON_FILES: ${{ inputs.additional-python-files }}
        uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c # v2.3.0
        with:
          filter: |
            python/**
            test/**/*.py
            tests/**/*.py
            noxfile.py
            pyproject.toml
            uv.lock
            .github/workflows/reusable-python-linter.yml
            .github/workflows/reusable-python-ci.yml
            .github/workflows/ci.yml
            .pre-commit-config.yaml
            ${{ env.ADDITIONAL_PYTHON_FILES }}
      - name: Set a flag for running the Python linter
        if: >-
          github.event_name != 'pull_request'
          || steps.changed-python-linter-files.outputs.all != ''
        id: python-linter-changes
        run: >-
          echo "run-python-linter=true" >> "${GITHUB_OUTPUT}"
      - name: Get a list of the changed files relevant for the continuous deployment job
        if: github.event_name == 'pull_request'
        id: changed-cd-files
        env:
          ADDITIONAL_CD_FILES: ${{ inputs.additional-cd-files }}
        uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c # v2.3.0
        with:
          filter: |
            .github/workflows/cd.yml
            ${{ env.ADDITIONAL_CD_FILES }}
      - name: Set a flag for running the continuous deployment job
        if: >-
          github.event_name == 'pull_request'
          && steps.changed-cd-files.outputs.all != ''
        id: cd-changes
        run: >-
          echo "run-cd=true" >> "${GITHUB_OUTPUT}"
